server:
  port: 9092
spring:
  datasource:
    url: jdbc:h2:mem:hotel
    username: hotel
    password: hotel
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  application:
    name: HOTEL-API
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
